# -*- coding: utf-8 -*-
"""ASSINGMENT5ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1RjSoE7DvJ3Xg3JVYRbEkBJTnx9PPvGv1
"""

import pandas as pd
import seaborn as sbs
states = ['CA', 'FL', 'TX', 'NY']
df = pd.read_csv('accident_100k.csv')
df = df[df['State'].isin(states)]
df

"""#TASK1"""

df['Date'] = pd.to_datetime(df['Weather_Timestamp']).dt.date
daily_counts = df.groupby(['State', 'Date']).size().reset_index(name='AccidentCount')
daily_counts

import matplotlib.pyplot as plt


plt.figure(figsize=(8,5))
for s in states:
    subset = daily_counts[daily_counts['State'] == s]
    plt.plot(subset['Date'], subset['AccidentCount'], label=s)

plt.xlabel('Date')
plt.ylabel('Daily Accident Count')
plt.title('Daily Accident Counts per State')
plt.legend()
plt.show()

"""Handling of Missing or Irregular Data:
The dataset contains missing or irregular accident records between August 2018 and April 2019.
To preserve the integrity of the original data, I chose to keep the gap visible in the time-series visualization rather than interpolating or modifying the counts.
This approach highlights real data coverage issues and helps show where accident reporting may have been incomplete.

#TASK2
"""

import seaborn as sns
df['DayOfWeek'] = df['Date'].dt.day_name()

weekday_density = (
    df.groupby('State')['DayOfWeek']
      .value_counts(normalize=True)
      .rename('Proportion')
      .reset_index()
)

heatmap_data = weekday_density.pivot(index='DayOfWeek', columns='State', values='Proportion')

plt.figure(figsize=(8,5))
sns.heatmap(heatmap_data, annot=True, cmap='YlOrRd', fmt=".2f")
plt.title('Accident Density by Day of Week and State')
plt.xlabel('State')
plt.ylabel('Day of Week')
plt.tight_layout()
plt.show()

"""The heatmap displays the proportion of daily accidents across weekdays for California (CA), Florida (FL), Texas (TX), and New York (NY).

- Weekday vs weekend contrast: All four states show far higher accident densities on weekdays (Monday–Friday) than on weekends (Saturday–Sunday), indicating strong commuter-traffic effects.

- Strongest contrast: California and Texas show the clearest weekday peaks—especially on Tuesday–Thursday, where proportions exceed 0.20, and sharp drops on weekends near 0.02–0.05.

- Florida and New York show a milder weekend drop but still follow the weekday-dominant trend.

- Unusual patterns: Monday accidents in Texas are relatively high, suggesting post-weekend travel or work-week restarts as a factor.

#TASK3
"""

weather_keep = ['Fair', 'Mostly Cloudy', 'Cloudy', 'Clear']
filtered = df[df['Weather_Condition'].isin(weather_keep)]

fig, axes = plt.subplots(2, 2, figsize=(12, 8))
axes = axes.flatten()

for i, state in enumerate(states):
    ax = axes[i]
    subset = filtered[filtered['State'] == state]

    sns.boxplot(
        x='Weather_Condition',
        y='Severity',
        data=subset,
        ax=ax,
        palette='Set2'
    )
    ax.set_title(f'Accident Severity in {state}')
    ax.set_xlabel('Weather Condition')
    ax.set_ylabel('Severity')
    ax.tick_params(axis='x', rotation=20)

plt.tight_layout()
plt.show()

"""- The four boxplots illustrate how accident severity changes under different weather conditions for California, Florida, Texas, and New York.
Severity levels are concentrated between 2 and 4 in all states, indicating that most accidents are of moderate seriousness.

- Weather effects: Fair and Clear conditions still account for many moderate-severity crashes, likely due to heavier traffic in good weather. Cloudy and Mostly Cloudy days show slightly higher upper-range severity possibly linked to reduced visibility or wet roads.

- State comparison: California exhibits more visible outliers at severity 4, suggesting occasional severe incidents even under normal conditions. Texas and New York display consistent distributions across weather types, while Florida shows a slightly higher median severity on Fair days, likely reflecting congestion and tourist activity.

- Overall, cloudy conditions marginally increase accident severity, but traffic volume and behavior remain key drivers of moderate to severe crashes across all four states.

#TASK4
"""

fig, axes = plt.subplots(2, 2, figsize=(10, 7))
axes = axes.flatten()

for i, state in enumerate(states):
    ax = axes[i]
    subset = df_task4[df_task4['State'] == state]

    sns.histplot(
        subset['Severity'],
        bins=[1, 2, 3, 4, 5],  # same range 1–4
        kde=False,
        color='steelblue',
        ax=ax
    )

    ax.set_title(f'Accident Severity Distribution in {state}')
    ax.set_xlabel('Severity Level')
    ax.set_ylabel('Frequency')
    ax.set_xlim(1, 4)
    ax.set_xticks([1, 2, 3, 4])
    ax.set_ylim(0, df_task4['Severity'].value_counts().max() * 1.1)

plt.tight_layout()
plt.show()

"""The histograms display how accident severity is distributed across California, Florida, Texas, and New York.

- Skew: All states show a strong left-skew, with the majority of cases at Severity 2, meaning most accidents are minor to moderate.

- Spikes: There is a large spike at Severity 2 across every state, followed by a sharp drop at higher levels (3–4).

- State differences: California has the highest overall frequency and a slightly thicker tail at Severity 3–4, suggesting more severe cases. Florida, Texas, and New York exhibit similar shapes, dominated by minor crashes with few severe ones.

- Gaps: Severity 1 is largely absent, indicating that very minor incidents were either unreported or excluded from this dataset.

Overall, accident severity distributions are heavily skewed toward low-severity events, with California showing a modestly greater proportion of severe accidents.

#TASK5
"""

df_task5 = df[(df['Visibility(mi)'] > 0) & (df['Visibility(mi)'] <= 20)]

plt.figure(figsize=(8,5))
sns.scatterplot(
    x='Visibility(mi)',
    y='Severity',
    data=df_task5,
    alpha=0.3,
    color='royalblue'
)

sns.regplot(
    x='Visibility(mi)',
    y='Severity',
    data=df_task5,
    scatter=False,
    color='red'
)


plt.title('Relationship Between Visibility and Accident Severity')
plt.xlabel('Visibility (miles)')
plt.ylabel('Accident Severity')
plt.tight_layout()
plt.show()

"""The scatterplot examines whether lower visibility corresponds to higher accident severity. A mild downward trend is visible, suggesting that accidents tend to be slightly more severe when visibility decreases. However, most data points cluster between 5 and 10 miles of visibility with moderate severities (2 to 3), meaning that visibility alone is not a strong predictor of severity. Overall, poor visibility increases risk marginally, but other environmental and behavioral factors likely have greater influence."""